# This is an example playbook to execute Ansible tests.
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include ach_mde_role"
      ansible.builtin.include_role:
        name: "ach_mde_role"
