# This is an example playbook to prepare Ansible tests.
---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include ach_mde_role"
      ansible.builtin.include_role:
        name: "ach_mde_role"
        tasks_from: prepare
